import {
  activatedDataSchema,
  completeRequestSchema,
  confirmContactRequestSchema,
  contactVerificationRequestSchema,
  eligibilityDataSchema,
  eligibilityRequestSchema,
  emptyRequestSchema,
  interestListDataSchema,
  legalDocumentListDataSchema,
  passwordRequestSchema,
  requiredDataRequestSchema,
  snapshotDataSchema,
  stageDataSchema,
  verificationWindowDataSchema,
  verifiedDataSchema,
} from '../../features/registration/contracts';
import type { BffOperation } from './bff-proxy';

/** Browser-facing operations and their single NestJS counterpart (SDD-010 §4.3). */
export const REGISTRATION_OPERATIONS = {
  eligibility: {
    operation: 'registration.eligibility',
    method: 'POST',
    backendPath: '/registration/eligibility',
    internal: true,
    requestSchema: eligibilityRequestSchema,
    responseSchema: eligibilityDataSchema,
    continuation: 'none',
    idempotency: 'optional',
    onSuccess: 'store',
  },
  requestVerification: {
    operation: 'registration.contact-verification',
    method: 'POST',
    backendPath: '/registration/contact-verification',
    internal: true,
    requestSchema: contactVerificationRequestSchema,
    responseSchema: verificationWindowDataSchema,
    continuation: 'required',
    idempotency: 'required',
    originFingerprint: true,
    onSuccess: 'store',
  },
  resendVerification: {
    operation: 'registration.contact-verification.resend',
    method: 'POST',
    backendPath: '/registration/contact-verification/resend',
    internal: true,
    requestSchema: emptyRequestSchema,
    responseSchema: verificationWindowDataSchema,
    continuation: 'required',
    idempotency: 'required',
    onSuccess: 'store',
  },
  confirmContact: {
    operation: 'registration.contact-verification.confirm',
    method: 'POST',
    backendPath: '/registration/contact-verification/confirm',
    internal: true,
    requestSchema: confirmContactRequestSchema,
    responseSchema: verifiedDataSchema,
    continuation: 'required',
    idempotency: 'required',
    onSuccess: 'store',
  },
  password: {
    operation: 'registration.password',
    method: 'PUT',
    backendPath: '/registration/password',
    internal: true,
    requestSchema: passwordRequestSchema,
    responseSchema: stageDataSchema,
    continuation: 'required',
    idempotency: 'required',
    onSuccess: 'store',
  },
  requiredData: {
    operation: 'registration.required-data',
    method: 'PUT',
    backendPath: '/registration/required-data',
    internal: true,
    requestSchema: requiredDataRequestSchema,
    responseSchema: stageDataSchema,
    continuation: 'required',
    idempotency: 'required',
    onSuccess: 'store',
  },
  snapshot: {
    operation: 'registration.snapshot',
    method: 'GET',
    backendPath: '/registration',
    internal: true,
    responseSchema: snapshotDataSchema,
    continuation: 'required',
    idempotency: 'none',
  },
  legalDocuments: {
    operation: 'registration.legal-documents',
    method: 'GET',
    backendPath: '/registration/legal-documents?locale=pt-BR',
    internal: true,
    responseSchema: legalDocumentListDataSchema,
    continuation: 'none',
    idempotency: 'none',
  },
  complete: {
    operation: 'registration.complete',
    method: 'POST',
    backendPath: '/registration/complete',
    internal: true,
    requestSchema: completeRequestSchema,
    responseSchema: activatedDataSchema,
    continuation: 'required',
    idempotency: 'required',
    onSuccess: 'expire',
  },
  interests: {
    operation: 'catalog.interests',
    method: 'GET',
    backendPath: '/catalog/interests?locale=pt-BR',
    internal: false,
    responseSchema: interestListDataSchema,
    continuation: 'none',
    idempotency: 'none',
  },
} as const satisfies Record<string, BffOperation>;
